### ISSUE TITLE
Recommended MP alphabet does not work in postgresql

### ISSUE THREAD

**Issue by zachmullen** [django-treebeard/django-treebeard#174]
django-treebeard version: 4.3.1

In my `MP_Node` subclass, the following works fine when creating a tree:

```python
alphabet = string.digits + string.ascii_uppercase + string.ascii_lowercase
```

However, [this page](https://django-treebeard.readthedocs.io/en/latest/mp_tree.html#treebeard.mp_tree.MP_Node.alphabet) recommends another alphabet:

> For an even better approach, change the collation of the path column in the database to handle raw ASCII, and use the printable ASCII characters (0x20 to 0x7E) as the alphabet.

But if I do that,

```python
alphabet = ''.join(chr(i) for i in range(0x20, 0x7f))
```

I get duplicate key errors, which I can only assume is a bug. Example:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "core_folder_path_key"
DETAIL:  Key (path)=(   !   !   &) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    main()
  File "./manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/djclick/adapter.py", line 68, in run_from_argv
    exit_code = self.main(
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/djclick/adapter.py", line 50, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/django/dkc/core/management/commands/mock_db.py", line 24, in command
    _populate_subtree(root_folder, depth - 1, branching)
  File "/opt/django/dkc/core/management/commands/mock_db.py", line 14, in _populate_subtree
    _populate_subtree(child, depth - 1, branching)
  File "/opt/django/dkc/core/management/commands/mock_db.py", line 13, in _populate_subtree
    folder.add_child(instance=child)  # equivalent to .save()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 1022, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 361, in process
    return self.node.get_last_child().add_sibling(
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 1037, in add_sibling
    return MP_AddSiblingHandler(self, pos, **kwargs).process()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 444, in process
    self.run_sql_stmts()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 147, in run_sql_stmts
    cursor.execute(sql, vals)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "core_folder_path_key"
DETAIL:  Key (path)=(   !   !   &) already exists.
```

In the above case, it consistently creates several rows before failing. Slightly changing the alphabet but preserving the non-alphanumeric characters causes it to continue to fail, but with differing row counts, leading me to believe this is a bug, probably to do with escaping.

**Comment by zachmullen** [comment]
I discovered a bit more about this bug. It's not a result of non-alphanumeric characters; it appears trying to use anything that isn't a prefix of `treebeard.numconv.BASE85` fails, though in different ways. Just changing to the following alphabet:

```python
alphabet = string.ascii_uppercase + string.ascii_lowercase + string.digits
```

causes this:

```
Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    main()
  File "./manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/djclick/adapter.py", line 68, in run_from_argv
    exit_code = self.main(
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/djclick/adapter.py", line 50, in invoke
    return super(DjangoCommandMixin, self).invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/django/dkc/core/management/commands/mock_db.py", line 24, in command
    _populate_subtree(root_folder, depth - 1, branching)
  File "/opt/django/dkc/core/management/commands/mock_db.py", line 14, in _populate_subtree
    _populate_subtree(child, depth - 1, branching)
  File "/opt/django/dkc/core/management/commands/mock_db.py", line 13, in _populate_subtree
    folder.add_child(instance=child)  # equivalent to .save()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 1022, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/usr/local/lib/python3.8/site-packages/treebeard/mp_tree.py", line 361, in process
    return self.node.get_last_child().add_sibling(
AttributeError: 'NoneType' object has no attribute 'add_sibling'
