### ISSUE TITLE
MP_Tree fails to update child counts after move operation.

### ISSUE THREAD

**Issue by zbyte64** [django-treebeard/django-treebeard#71]
I have the following code that checks for problems, fetches two nodes, moves one to the other, and then performs another check.

```
probs = Concept.find_problems()
assert not any(probs), str(probs)
parent = Concept.objects.get(pk=parent.id)
concept = Concept.objects.get(pk=concept.id)
concept.move(parent, 'sorted-child')

probs = Concept.find_problems()
assert not any(probs), str(probs)
```

The result is a failure in the last assertion and treebeard tells us it is because a child count is off.

```
Moving existing concept so that: 'Ecology and environment' > 'Ecology'
Was: Biology and life sciences
([], [], [], [], [1125])
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/code/apps/focus/management/commands/import_skos_vocabulary.py", line 326, in handle
    mash_concept(k, c)
  File "/code/apps/focus/management/commands/import_skos_vocabulary.py", line 222, in mash_concept
    assert not any(probs), str(probs)
AssertionError: ([], [], [], [], [1125])
```

Relevant version numbers:
django==1.10.6
django-treebeard==4.1.2

**Comment by tabo** [comment]
This seems really strange. Could you please share the rest of your test if you still have it around?

It looks to me like a problem with `Manager` subclassing. One of the warnings in https://django-treebeard.readthedocs.io/en/latest/mp_tree.htm:

> If you need to define your own Manager class, you’ll need to subclass MP_NodeManager.
> 
> Also, if in your manager you need to change the default queryset handler, you’ll need to subclass MP_NodeQuerySet.
